### ISSUE TITLE
Choose another documentation theme

### ISSUE THREAD

**Issue by isaak654** [DavidXanatos/sandboxie-docs#102]
#### _Originally posted by @SiNONiMiTY in https://github.com/sandboxie-plus/sandboxie-docs/issues/54#issuecomment-1221636461_
> Do you think we can rewrite the sandboxie documentation using the ReadTheDocs format?
> 
> Take a look at the documentation of Unbound, a recursive dns server that has a lot of options:
> https://unbound.docs.nlnetlabs.nl/en/latest/
> 
> I think this documentation format is very readable. Given that sandboxie has a lot of options, we can document it in this format.

### Requested theme
- https://github.com/readthedocs/sphinx_rtd_theme

### Alternative themes to consider
- https://github.com/just-the-docs/just-the-docs
- https://github.com/mkdocs/mkdocs

### Recommendations for contributors
- Avoid breaking existing pages and current links such as https://sandboxie-plus.github.io/sandboxie-docs/Content/ResourceAccess.html
- If the suggested themes are not of your liking, feel free to suggest a new one

This issue is not in my plans, but if someone wanted to attach a pull request, that would be cool.

**Comment by QZLin** [comment]
What about this? ~~[Sandboxie Documentation](https://qzlin.github.io/sandboxie-docs-site/)~~(moved to https://qzlin.github.io/sandboxie-docs)
Generated by mkdocs with readthedocs theme
(repo here: https://github.com/QZLin/sandboxie-docs/)

**Comment by isaak654** [comment]
Theme is very good looking, I would suggest some improvements if possible:
- search feature has no highlighting, it would be great if you could adopt the mkdocs search provided in [this sample](https://www.hexo.dev/sandboxie-docs) (repository: https://github.com/okrc/sandboxie-docs)
- it would be ideal to replace [the link](https://github.com/sandboxie-plus/sandboxie-docs/assets/12372772/e8ba7cc7-57cc-44eb-8f22-ab849b3eec04) above the search bar with a transparent version of the [Sandboxie logo](https://user-images.githubusercontent.com/3890945/105014988-575cb680-5a41-11eb-90d5-d942d28184b2.png), as long as it remains linkable (of course other Sandboxie logos would be fine too).
- Footer should contain a [View source code](https://github.com/sandboxie-plus/sandboxie-docs) link or similar wording to incentivate contributions in the base repository. Also, it should contain the following references:
![Footer jekyll-theme-cayman theme](https://github.com/sandboxie-plus/sandboxie-docs/assets/12372772/18caebbc-5d93-45c7-8b3e-ca2e9c91a4fe)
The last one in particular allows to edit the same displayed page without effort, which is a nice bonus.

**Comment by isaak654** [comment]
Theme is very good looking, I would suggest some improvements if possible:
- search feature has no highlighting and is not a fixed element of the page (especially when you scroll the left column). For these reasons, it would be great if you could adopt the mkdocs search provided in [this sample](https://www.hexo.dev/sandboxie-docs) (repository: https://github.com/okrc/sandboxie-docs)
- it would be ideal to replace [the link](https://github.com/sandboxie-plus/sandboxie-docs/assets/12372772/e8ba7cc7-57cc-44eb-8f22-ab849b3eec04) above the search bar with a transparent version of the [Sandboxie logo](https://user-images.githubusercontent.com/3890945/105014988-575cb680-5a41-11eb-90d5-d942d28184b2.png), as long as it remains linkable (of course other Sandboxie logos would be fine too).
- Footer should contain a [View source code](https://github.com/sandboxie-plus/sandboxie-docs) link or similar wording to incentivate contributions in the base repository. Also, it should contain the following references:
![Footer jekyll-theme-cayman theme](https://github.com/sandboxie-plus/sandboxie-docs/assets/12372772/18caebbc-5d93-45c7-8b3e-ca2e9c91a4fe)
The last one in particular allows to edit the same displayed page without effort, which is a nice bonus.

**Comment by isaak654** [comment]
Theme is very good looking, I would suggest some improvements if possible:
- search feature has no highlighting and is not a fixed element of the page (especially when you scroll the left column). For these reasons, it would be great if you could adopt the mkdocs search provided in [this sample](https://www.hexo.dev/sandboxie-docs) (repository: https://github.com/okrc/sandboxie-docs)
- it would be ideal to replace [the link](https://user-images.githubusercontent.com/12372772/271982749-e8ba7cc7-57cc-44eb-8f22-ab849b3eec04.png) above the search bar with a transparent version of the [Sandboxie logo](https://user-images.githubusercontent.com/3890945/105014988-575cb680-5a41-11eb-90d5-d942d28184b2.png), as long as it remains linkable (of course other Sandboxie logos would be fine too).
- Footer should contain a [View source code](https://github.com/sandboxie-plus/sandboxie-docs) link or similar wording to incentivate contributions in the base repository. Also, it should contain the following references:
![Footer jekyll-theme-cayman theme](https://github.com/sandboxie-plus/sandboxie-docs/assets/12372772/18caebbc-5d93-45c7-8b3e-ca2e9c91a4fe)
The last one in particular allows to edit the same displayed page without effort, which is a nice bonus.

**Comment by stdedos** [comment]
There is also a newer template of the https://sphinx-rtd-theme.readthedocs.io/en/stable/: https://pylint.readthedocs.io/en/stable/

What is the status of this one by the way? I'd be interested to learn how ReadTheDocs works - or contribute changes / borrow existing commits to build a result.

**Comment by stdedos** [comment]
The theme shown above is "Furo" (https://github.com/pytest-dev/pytest-cov/issues/618)
