### ISSUE TITLE
Website hard to navigate. feedback

### ISSUE THREAD

**Issue by kokofixcomputers** [DavidXanatos/sandboxie-docs#148]
I feel like that the sandboxie website (https://sandboxie-plus.com/) is a little bit disorganized and like i can't find the docs on the website even though the docs readme (this GitHub repo) says that it is available there. I also feel like i (if i'm paying) will pay more if the website is more styled. If you want my help @DavidXanatos, feel free to email me. BUT THIS IS ONLY A SUGGESTION AND FROM MY OWN PERSPECTIVE. MOST PEOPLE MAY OR MAY NOT THINK MY WAY. I just feel like this app is awesome and people here have been kind to me and fast (especially DavidXanatos) so i want to help some way (not paying) Feel free to tell me what i can help with DavidXanatos.

**Comment by offhub** [comment]
https://github.com/sandboxie-plus/Sandboxie/blob/master/CONTRIBUTING.md

**Comment by DavidXanatos** [comment]
a good starting point for the cox is: https://sandboxie-plus.com/sandboxie/allpages/
but yes its highly unorganized, so if you want to help with improving the website organization and layout that would be really awesome.
I don't see your email in your github profile so you will need to email me first ;)

**Comment by kokofixcomputers** [comment]
Sure! How would you like me to help organize? Should I copy your html and modify it?

**Comment by DavidXanatos** [comment]
got your email, great
how to best progress depands on your skills et are you familiar with wordpress?
Currently most of the pages are writen in mark down and a WP plugin generates the html from that.

I think first whats needes is a comcept what to present where which menus etc, in can easely set this once I know how that should look, than we can procees with adding new pages and content which glue all that together.

**Comment by kokofixcomputers** [comment]
Well i used it before.

**Comment by kokofixcomputers** [comment]
What happened to the site? it wasn't like this yesterday

**Comment by kokofixcomputers** [comment]
<img width="2240" alt="Screenshot 2024-01-05 at 10 30 40 AM" src="https://github.com/sandboxie-plus/sandboxie-docs/assets/113046561/24a15b16-7506-4c9d-88cb-0a642e4e855d">

**Comment by DavidXanatos** [comment]
I moved the menu links for priv10 and wumgr to a new sub group old software and added a new menu link to the new aMajor Privacy repository.

the page you linked did not change recently IIRC

**Comment by kokofixcomputers** [comment]
> I moved the menu links for priv10 and wumgr to a new sub group old software and added a new menu link to the new aMajor Privacy repository.
> 
> the page you linked did not change recently IIRC

Nice. Maybe i will go back to my new computer because this one is weird on your site

**Comment by DavidXanatos** [comment]
wired how?

**Comment by kokofixcomputers** [comment]
> wired how?

You see, in the screenshot one side of the page is blank while the other is okay

**Comment by kokofixcomputers** [comment]
Okay. I'm back on the new computer

**Comment by kokofixcomputers** [comment]
@DavidXanatos Would be happy to help!

**Comment by DavidXanatos** [comment]
Well lets start, I think the first thing would be to add some more entries to the nav menu on the side pointing to the documentaiton index as well as important doc pages.
Perhaps create a few new summary pages.

If you create a mock up what should go where than I'll create the links in the menu and the summary pages can be created here on github and they will be synced with the website.

Also would you be willing to help with the website for the other projects?

**Comment by kokofixcomputers** [comment]
> Well lets start, I think the first thing would be to add some more entries to the nav menu on the side pointing to the documentaiton index as well as important doc pages. Perhaps create a few new summary pages.

> 
I agree
> If you create a mock up what should go where than I'll create the links in the menu and the summary pages can be created here on github and they will be synced with the website.
>
so i create a basic md or txt file saying what should go where?
> 
> Also would you be willing to help with the website for the other projects?

Yes i would be.

**Comment by DavidXanatos** [comment]
Yea a txt would be best depicting the new nav menu hierarchy with labels and links

**Comment by kokofixcomputers** [comment]
> Yea a txt would be best depicting the new nav menu hierarchy with labels and links

Okay, where should i put it?

**Comment by kokofixcomputers** [comment]
Do you have a repo?

**Comment by DavidXanatos** [comment]
for sandboxie its this repo we are in right now

**Comment by kokofixcomputers** [comment]
> for sandboxie its this repo we are in right now

Okay, i will be busy for at least one hour to 12 (i think) my time

**Comment by DavidXanatos** [comment]
ok I'll wait here its only 20:00 hours

**Comment by kokofixcomputers** [comment]
> ok I'll wait here its only 20:00 hours

Thank you for your patience

**Comment by kokofixcomputers** [comment]
I’m troubleshooting another issue but I will be here soon. Sorry for being delayed. Someone is helping me troubleshoot.

**Comment by kokofixcomputers** [comment]
> Yea a txt would be best depicting the new nav menu hierarchy with labels and links

@DavidXanatos I'm back! check email
