### ISSUE TITLE
WriteFilePath did not work for files

### ISSUE THREAD

**Issue by hulinfan** [DavidXanatos/sandboxie-docs#166]
I would like to hide some files outside the sandbox. For example:
```
WriteFilePath=D:\tmp\a.txt
```
But it doesn't work. I check the docs about write file path:  
https://sandboxie-website-archive.github.io/www.sandboxie.com/WriteFilePath.html 

Got that  the file is treated as if it matches a ClosedFilePath. 

My question is,  it seems not technical hard to implement, but why 'WriteFilePath' not supports file? What's the aspect i've been missing?

**Comment by offhub** [comment]
I don't know the reason, but you can try the following methods.

## For Sandboxie-Plus:
### You can delete the file or create an empty copy of it from the sandbox using the Triggers feature.

#### delete:

```ini
AutoExec=cmd /c "del "<drive>:\<path>\<file>""
``` 

OR

#### empty copy:

```ini
AutoExec=cmd /c "type NUL > "<drive>:\<path>\<file>""
``` 

See [AutoExec](https://sandboxie-plus.github.io/sandboxie-docs/Content/AutoExec.html)

AND/OR

### You can use the Snapshot feature.

1. Run sandboxed CMD.
2. Delete the file (or change the contents of the file).
2. Close sandboxed CMD.
3. `Right-click the sandbox > Sandbox Options > Snapshot Manager > Take Snapshot`
4. Unless you delete the snapshots, the files in that snapshot remain valid even if the contents of the box are deleted.
    - You can add files to the appropriate locations under `Sandbox\Box\snapshot-x` using unsandboxed Windows Explorer.

See [BoxSnapshots](https://sandboxie-plus.github.io/sandboxie-docs/PlusContent/BoxSnapshots.html)

**Comment by hulinfan** [comment]
> I don't know the reason, but you can try the following methods.
> 
> ## For Sandboxie-Plus:
> ### You can delete the file or create an empty copy of it from the sandbox using the Triggers feature.
> #### delete:
> ```ini
> AutoExec=cmd /c "del "<drive>:\<path>\<file>""
> ```
> 
> OR
> 
> #### empty copy:
> ```ini
> AutoExec=cmd /c "type NUL > "<drive>:\<path>\<file>""
> ```
> 
> See [AutoExec](https://sandboxie-plus.github.io/sandboxie-docs/Content/AutoExec.html)
> 
> AND/OR
> 
> ### You can use the Snapshot feature.
> 1. Run sandboxed CMD.
> 2. Delete the file (or change the contents of the file).
> 3. Close sandboxed CMD.
> 4. `Right-click the sandbox > Sandbox Options > Snapshot Manager > Take Snapshot`
> 5. Unless you delete the snapshots, the files in that snapshot remain valid even if the contents of the box are deleted.
>    
>    * You can add files to the appropriate locations under `Sandbox\Box\snapshot-x` using unsandboxed Windows Explorer.
> 
> See [BoxSnapshots](https://sandboxie-plus.github.io/sandboxie-docs/PlusContent/BoxSnapshots.html)

Thanks offhub. Your information helps me a lot.
