### ISSUE TITLE
ProcessLimit got added back again in 0.9.7

### ISSUE THREAD

**Issue by bastik-1001** [DavidXanatos/sandboxie-docs#57]
It got integrated again in [0.9.7](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.7).
> - added "ProcessLimit=..." that allows to limit the max count of processes in a sandbox [#1230](https://github.com/sandboxie-plus/Sandboxie/issues/1230)

Is [Process Limit 1](https://sandboxie-plus.github.io/sandboxie-docs/Content/ProcessLimit1.html) to be updated to state that a similar feature got added again? Either by pointing to, yet to create, ProcessLimit.md or by adding a section to it, that says a line or two about the newly added ProcessLimit?

**Comment by isaak654** [comment]
A new ProcessLimit.md page is still preferable in the long term (a contributor certificate should be feasible for it), however I've added proper warnings in https://github.com/sandboxie-plus/sandboxie-docs/pull/124
