### ISSUE TITLE
A number of typos found by Codespell

### ISSUE THREAD

**Issue by isaak654** [DavidXanatos/sandboxie-docs#61]
Any PR aimed to fix these typos would be appreciated:

> Error: ./Content/ForceProcess.md:3: progams ==> programs
> Error: ./Content/SBIE9304.md:12: messsage ==> message
> Error: ./Content/SandboxieIni.md:63: overriden ==> overridden
> Error: ./Content/SandboxieIni.md:64: overriden ==> overridden
> Error: ./Content/SandboxieIni.md:69: setion ==> section
> Error: ./Content/SandboxieIni.md:73: overriden ==> overridden
> Error: ./Content/MessagesFromSandboxie.md:13: progam ==> program
> Error: ./Content/SBIE2102.md:14: noticable ==> noticeable
> Error: ./Content/ClosedFilePath.md:3: progams ==> programs
> Error: ./Content/PlusMigrationGuide.md:33: comand ==> command
> Error: ./Content/PlusMigrationGuide.md:75: depecated ==> deprecated
> Error: ./Content/PlusMigrationGuide.md:165: Aditionally ==> Additionally
> Error: ./Content/GettingStartedPartSix.md:15: inter-operability ==> interoperability
> Error: ./Content/GettingStartedPartSix.md:33: inter-operability ==> interoperability
> Error: ./Content/SBIE1204.md:10: ocurred ==> occurred
> Error: ./Content/SBIE1101.md:9: successfuly ==> successfully
> Error: ./Content/ProgramsView.md:7: colums ==> columns
> Error: ./Content/FAQEmail.md:7: informaion ==> information
> Error: ./Content/SBIE9302.md:11: messsage ==> message
> Error: ./Content/HowToUseWinDbg.md:68: occured ==> occurred
> Error: ./Content/StartCommandLine.md:186: cancelation ==> cancellation
> Error: ./Content/SandboxHierarchy.md:51: struture ==> structure
> Error: ./Content/ExpandableVariables.md:58: overriden ==> overridden
> Error: ./Content/ClosedKeyPath.md:3: progams ==> programs
> Error: ./Content/SBIE1116.md:9: accomodate ==> accommodate
> Error: ./Content/SandboxMenu.md:75: comobobox ==> combo-box
> Error: ./Content/SandboxMenu.md:83: commmand ==> command
> Error: ./Content/SandboxMenu.md:83: useable ==> usable
> Error: ./Content/SBIE2108.md:11: ocurring ==> occurring
> Error: ./Content/FrequentlyAskedQuestions.md:46: metaphore ==> metaphor
> Error: ./Content/FrequentlyAskedQuestions.md:143: Mutexs ==> Mutexes
> Error: ./Content/SystemEventLog.md:3: whichs ==> which's
> Error: ./Content/PaperAnalogy.md:13: metaphore ==> metaphor
> Error: ./Content/SandboxieTrace.md:113: accessability ==> accessibility
> Error: ./Content/ClosedIpcPath.md:3: progams ==> programs

**Comment by Luro223** [comment]
@isaak654 I will fix by one per pull request

**Comment by Luro223** [comment]
Done #63 #64 #65 #66 #67 #68 #69 #70 #71 #72 #73 #74 #75 #76 #77 #78 #79 #80 #81 #82 #83 #84 #85 #86 #87 #88

**Comment by Luro223** [comment]
Did additional typos fix

**Comment by Luro223** [comment]
@isaak654 need review for #66

**Comment by Luro223** [comment]
and #69

**Comment by Luro223** [comment]
Yeah, finally no Codespell typo issues
