### ISSUE TITLE
other restrictions and open system protected storage What menu is it?

### ISSUE THREAD

**Issue by oklokl** [DavidXanatos/sandboxie-docs#97]
![1](https://user-images.githubusercontent.com/1571600/197088531-d08c8d5e-b758-452e-be3d-51d5fae4db4d.png)
What does this mean?
Is it enhanced security?.

Or is it to allow security?.
For system connection.

Or is it allowed without security?
Bad choice for security?. (Choosing security poorly)

My curiosity is by allowing credentials. Will it compromise security?

Or, I wonder if security is enhanced by selecting credentials.

I want to enhance security.

**Comment by isaak654** [comment]
https://github.com/sandboxie-plus/sandboxie-docs/blob/main/docs/Content/OpenProtectedStorage.md
https://github.com/sandboxie-plus/sandboxie-docs/blob/main/docs/Content/OpenCredentials.md
https://www.wilderssecurity.com/threads/openprotectedstorage-and-opencredentials.448257/
