### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by harryray33** [DavidXanatos/sandboxie-docs#99]
Do both versions, Classic and Plus, work with Win 7?

Is there offline documentation that I can download, or is it all online?

Thanks.

**Comment by isaak654** [comment]
1. [System requirements](https://github.com/sandboxie-plus/Sandboxie#readme) table
2. It's all online

**Comment by isaak654** [comment]
1. [System requirements](https://github.com/sandboxie-plus/Sandboxie#readme) table cell
2. It's all online
